name: 自动更新文件

on:
  push:
    branches: [ master ]
  schedule:
    - cron: 5 12,22 * * *
  watch:
    types: started

jobs:
  tieba_sign:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Set python'
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: 'Install dependencies'
        run: python -m pip install --upgrade requests
      - name: 'Start update'
        run: python festival.py
